name: Compilation
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y cmake
      # - name: Compile
      #   run: mkdir build && cmake -S . -B build && cmake --build build
