name: Push to Destination Repository
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/*'
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Push to Destination Repository
        env:
          DESTINATION_REPO_TOKEN: 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
        run: |
          git config --global user.email "clovis.rabot@epitech.eu"
          git config --global user.name "rclovis"

          git clone https://github.com/rclovis/R-Type-Documentation.git

          rm -fr R-Type-Documentation/r-type/docs
          cp -r docs R-Type-Documentation/r-type

          cd R-Type-Documentation

          git add .
          git commit -m "Update from source repository"
          git push https://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@github.com/rclovis/R-Type-Documentation.git HEAD:main